meta_product_name: "K-reer"
meta_title: "K-reer - Scale Your K-reer"
meta_description: "The app reorganize your IT recruitment process-Scale Your K-reer"
meta_image: "reactjs.jpg" # devrait exister dans `app / assets / images /`
twitter_account: "@product_twitter_account" # requis pour les cartes Twitter
